"""
TA Swap Strategy: keeperhub_swap_agent

Technical analysis swap strategy with configurable RSI, Bollinger Bands, or combined signals

Generated by: almanak strat new
Template: ta_swap
Chain: arbitrum
Created: 2026-09-15T19:17:22.276574

Strategy Pattern:
-----------------
1. Inherit from IntentStrategy
2. Use @almanak_strategy decorator for metadata
3. Implement decide(market) method that returns an Intent
4. The framework handles compilation and execution
"""

import logging
from datetime import date, datetime
from decimal import ROUND_DOWN, Decimal  # noqa: F401 - ROUND_DOWN used by lending template only
from enum import Enum
from typing import Any

# Core strategy framework imports
from almanak.framework.intents import AnyIntent, Intent
from almanak.framework.market import MarketSnapshot
from almanak.framework.strategies import (
    DecideResult,
    IntentStrategy,
    almanak_strategy,
)

logger = logging.getLogger(__name__)


def _safe(v: Any) -> Any:
    """Normalise a ``get_status()`` field into a JSON-serialisable primitive.

    Called by the generated ``get_status()`` on every value that comes out of
    ``_last_position_snapshot`` (which strategies populate with whatever types
    they like — raw Decimal prices, datetime timestamps, Enum signals, ...).
    Without this, ``json.dumps(strategy.get_status())`` on an operator
    dashboard would crash the first time a snapshot carried a Decimal or a
    datetime.
    """
    if v is None:
        return None
    if isinstance(v, Decimal):
        return str(v)
    if isinstance(v, datetime | date):
        return v.isoformat()
    if isinstance(v, Enum):
        return getattr(v, "value", str(v))
    return v



@almanak_strategy(
    name="keeperhub_swap_agent",
    description="Technical analysis swap strategy with configurable RSI, Bollinger Bands, or combined signals",
    version="1.0.0",
    author="Generated",
    tags=["generated", "ta_swap"],
    supported_chains=["arbitrum"],
    supported_protocols=["uniswap_v3"],
    intent_types=["SWAP", "HOLD"],
    default_chain="arbitrum",
    quote_asset="USD",  # performance denomination; token form only for accumulators
)
class KeeperhubSwapAgentStrategy(IntentStrategy):
    """
    Technical analysis swap strategy with configurable RSI, Bollinger Bands, or combined signals

    Chain: arbitrum
    Protocol: uniswap_v3

    Configuration Parameters:
    -------------------------
    See config.json for configurable parameters.
    """

    def __init__(self, *args, **kwargs):
        """
        Initialize the strategy with configuration.

        The base class (IntentStrategy) handles:
        - self.config: Strategy configuration (dict or dataclass)
        - self.chain: The blockchain to operate on
        - self.wallet_address: The wallet executing trades
        """
        super().__init__(*args, **kwargs)

        # Helper to get config value from dict or object attributes
        def get_config(key: str, default: Any) -> Any:
            if isinstance(self.config, dict):
                return self.config.get(key, default)
            return getattr(self.config, key, default)

        # Indicator mode: "rsi", "bollinger", or "rsi_bb" (combined)
        self._indicator = get_config("indicator", "rsi")

        # RSI parameters
        self.rsi_period = int(get_config("rsi_period", 14))
        self.rsi_oversold = Decimal(str(get_config("rsi_oversold", "30")))
        self.rsi_overbought = Decimal(str(get_config("rsi_overbought", "70")))

        # Bollinger Bands parameters
        self.bb_period = int(get_config("bb_period", 20))
        self.bb_std_dev = float(get_config("bb_std_dev", 2.0))
        self.squeeze_threshold = float(get_config("squeeze_threshold", 0.02))
        self.buy_percent_b = float(get_config("buy_percent_b", 0.0))
        self.sell_percent_b = float(get_config("sell_percent_b", 1.0))

        # Trading parameters
        self.trade_size_usd = Decimal(str(get_config("trade_size_usd", "1000")))
        self.max_slippage_bps = int(get_config("max_slippage_bps", 50))

        # Gas-worthiness gate:
        #   min_trade_value_usd: absolute floor below which a trade is skipped
        #   max_gas_ratio: reject trades where gas_cost > this fraction of trade value
        self.min_trade_value_usd = Decimal(str(get_config("min_trade_value_usd", "10")))
        self.max_gas_ratio = Decimal(str(get_config("max_gas_ratio", "0.05")))

        # Token configuration
        self.base_token = get_config("base_token", "WETH")
        self.quote_token = get_config("quote_token", "USDC")

        # Dust floor (USD) above which the wallet is considered to be HOLDING
        # base. Used to reconcile the cached `_holding_base` flag against live
        # balance (VIB-5155 / ALM-2719) so rounding dust isn't treated as an
        # open position.
        self.holding_dust_usd = Decimal(str(get_config("holding_dust_usd", "1")))

        # Position tracking. The cached flag is a HINT; live balance is the
        # source of truth and is reconciled each cycle / on resume / before
        # teardown via _reconcile_holding_base() (VIB-5155 / ALM-2719).
        self._holding_base = False
        # Neutral-rearm latch: last signal we acted on (buy/sell/neutral)
        self._last_signal = 'neutral'

        logger.info(f"KeeperhubSwapAgentStrategy initialized on {self.chain}")

    def decide(self, market: MarketSnapshot) -> DecideResult:
        """
        Make a trading decision based on current market conditions.

        This is the core method of the strategy. It's called by the framework
        on each iteration with fresh market data.

        Parameters:
            market: MarketSnapshot containing:
                - market.price(token): Get current price in USD
                - market.rsi(token, period): Get RSI indicator
                - market.balance(token): Get wallet balance
                - market.chain: Current chain
                - market.wallet_address: Current wallet

        Returns:
            DecideResult: What action to take
                - Intent.swap(...): Execute a swap
                - Intent.hold(...): Do nothing
                - Intent.sequence([...]): Execute dependent intents in order
                - None: Also means hold
        """
        try:
            indicator = getattr(self, '_indicator', 'rsi')

            # Get balances
            try:
                quote_balance = market.balance(self.quote_token)
                base_balance = market.balance(self.base_token)
            except ValueError as e:
                logger.warning(f"Could not get balances: {e}")
                return Intent.hold(reason="Balance data unavailable")

            # Reconcile the cached position-side flag against live balance each
            # cycle: the persisted `_holding_base` flag is only a HINT; the live
            # wallet balance is TRUTH. Without this, a stale/false flag (e.g.
            # after a restart whose runtime state desynced) could HOLD-lock a
            # valid risk-off exit even though the wallet actually holds base.
            # See VIB-5155 / ALM-2719.
            self._reconcile_holding_base(market, base_balance=base_balance)

            buy_signal = False
            sell_signal = False
            reason = ""

            # RSI analysis
            if indicator in ("rsi", "rsi_bb"):
                try:
                    rsi = market.rsi(self.base_token, period=self.rsi_period)
                    if rsi.value <= self.rsi_oversold:
                        buy_signal = True
                        reason = f"RSI oversold ({rsi.value:.1f})"
                    elif rsi.value >= self.rsi_overbought:
                        sell_signal = True
                        reason = f"RSI overbought ({rsi.value:.1f})"
                    else:
                        reason = f"RSI neutral ({rsi.value:.1f})"
                except ValueError as e:
                    logger.warning(f"RSI unavailable: {e}")
                    return Intent.hold(reason="RSI data unavailable")

            # Bollinger Bands analysis
            if indicator in ("bollinger", "rsi_bb"):
                try:
                    bb = market.bollinger_bands(self.base_token, period=self.bb_period, std_dev=self.bb_std_dev)
                    if bb.bandwidth < self.squeeze_threshold:
                        return Intent.hold(reason=f"BB squeeze (bandwidth={bb.bandwidth:.4f})")
                    bb_buy = bb.percent_b <= self.buy_percent_b
                    bb_sell = bb.percent_b >= self.sell_percent_b
                    if indicator == "bollinger":
                        buy_signal = bb_buy
                        sell_signal = bb_sell
                        reason = f"%B={bb.percent_b:.4f}"
                    elif indicator == "rsi_bb":
                        buy_signal = buy_signal and bb_buy
                        sell_signal = sell_signal and bb_sell
                        reason += f", %B={bb.percent_b:.4f}"
                except ValueError as e:
                    logger.warning(f"BB unavailable: {e}")
                    if indicator == "bollinger":
                        return Intent.hold(reason="BB data unavailable")
                    # rsi_bb mode: falling back to RSI-only signals
                    logger.warning("Bollinger Bands unavailable in rsi_bb mode -- falling back to RSI-only signals")

            # Neutral re-arm: act only when a signal first appears, not every tick
            # the indicator stays in the extreme zone. Reset to neutral here when
            # there's no signal; the buy/sell latch is set in on_intent_executed on
            # a SUCCESSFUL swap, so a held-back (gas/balance) or failed swap never
            # locks out the next attempt.
            current_signal = "buy" if buy_signal else "sell" if sell_signal else "neutral"
            if current_signal == "neutral":
                self._last_signal = "neutral"
                return Intent.hold(reason=reason or "No signal")
            if current_signal == self._last_signal:
                return Intent.hold(
                    reason=f"{reason} -- already acted on this {current_signal} signal; awaiting neutral reset"
                )

            if buy_signal and quote_balance.balance_usd >= self.trade_size_usd:
                # Gas-worthiness gate: don't pay $5 gas to move $1. Authors can
                # tune via `min_trade_value_usd` (absolute floor) and
                # `max_gas_ratio` (dynamic ratio) in config.json.
                if self.trade_size_usd < self.min_trade_value_usd:
                    return Intent.hold(
                        reason=f"trade size ${self.trade_size_usd} below min_trade_value_usd "
                        f"${self.min_trade_value_usd}"
                    )
                if not market.is_trade_worthwhile(
                    amount_usd=self.trade_size_usd,
                    chain=market.chain,
                    max_gas_ratio=self.max_gas_ratio,
                ):
                    gas_cost = market.estimate_swap_gas_cost_usd(market.chain)
                    return Intent.hold(
                        reason=f"gas cost ${gas_cost} exceeds {self.max_gas_ratio:.2%} of trade value "
                        f"${self.trade_size_usd}"
                    )
                logger.info(f"BUY: {reason}")
                return Intent.swap(
                    from_token=self.quote_token,
                    to_token=self.base_token,
                    amount_usd=self.trade_size_usd,
                    max_slippage=Decimal(str(self.max_slippage_bps)) / Decimal("10000"),
                )
            elif sell_signal:
                base_price = market.price(self.base_token)
                # An unpriced market cannot SIZE a sell. Treating price <= 0 as
                # "min_sell = 0" is not a safe fallback: it makes the balance
                # check below pass on ANY dust, so the strategy emits a SWAP at
                # the full configured notional off a $0 oracle. Empty != Zero --
                # refuse rather than substitute a zero for a number you do not
                # have. (The buy branch is gated by `quote_balance.balance_usd`,
                # which a degraded oracle already drags to 0.)
                if not base_price or base_price <= 0:
                    return Intent.hold(
                        reason=f"No valid {self.base_token} price ({base_price}); refusing to size a sell"
                    )
                min_sell = self.trade_size_usd / base_price
                if base_balance.balance >= min_sell:
                    # Gas-worthiness gate (same as buy branch).
                    if self.trade_size_usd < self.min_trade_value_usd:
                        return Intent.hold(
                            reason=f"trade size ${self.trade_size_usd} below min_trade_value_usd "
                            f"${self.min_trade_value_usd}"
                        )
                    if not market.is_trade_worthwhile(
                        amount_usd=self.trade_size_usd,
                        chain=market.chain,
                        max_gas_ratio=self.max_gas_ratio,
                    ):
                        gas_cost = market.estimate_swap_gas_cost_usd(market.chain)
                        return Intent.hold(
                            reason=f"gas cost ${gas_cost} exceeds {self.max_gas_ratio:.2%} of trade value "
                            f"${self.trade_size_usd}"
                        )
                    logger.info(f"SELL: {reason}")
                    return Intent.swap(
                        from_token=self.base_token,
                        to_token=self.quote_token,
                        amount_usd=self.trade_size_usd,
                        max_slippage=Decimal(str(self.max_slippage_bps)) / Decimal("10000"),
                    )

            return Intent.hold(reason=reason or "No signal")

        except Exception as e:
            logger.exception(f"Error in decide(): {e}")
            return Intent.hold(reason=f"Error: {str(e)}")

    def get_status(self) -> dict[str, Any]:
        """Get current strategy status for monitoring/dashboards.

        Pure accessor: reads only instance state (no gateway calls, no I/O).
        Returned values are JSON-safe (Decimal->str, datetime->isoformat,
        StrEnum->str via getattr(.value, fallback)).
        """
        status: dict[str, Any] = {
            "strategy": "keeperhub_swap_agent",
            "chain": self.chain,
            "wallet": self.wallet_address[:10] + "..." if self.wallet_address else None,
        }
        snapshot = getattr(self, "_last_position_snapshot", None) or {}
        status.update(
            {
                "state": "holding_base" if self._holding_base else "holding_quote",
                "holding_base": self._holding_base,
                "base_token": self.base_token,
                "quote_token": self.quote_token,
                "indicator": self._indicator,
                "last_signal": _safe(snapshot.get("last_signal")),
                "last_trade_ts": _safe(snapshot.get("last_trade_ts")),
            }
        )
        return status

    def _reconcile_holding_base(self, market, base_balance=None):
        """Re-derive the cached `_holding_base` flag from live balance.

        The persisted `_holding_base` flag is only a HINT. The wallet's
        live base-token balance is the source of truth. A stale/false
        flag (e.g. after a restart whose runtime state desynced) must
        never HOLD-lock a valid risk-off exit, so every cycle / resume /
        teardown reconciles the flag from the live snapshot before any
        decision is made (VIB-5155 / ALM-2719).

        Returns True if the flag disagreed with live balance and was
        corrected, False if it already agreed, and None if the live
        balance could not be read (flag left untouched).
        """
        try:
            if base_balance is None:
                base_balance = market.balance(self.base_token)
            native = base_balance.balance
            usd = base_balance.balance_usd
        except (ValueError, AttributeError) as e:
            # Live balance unavailable: keep the cached hint, do not flip.
            logger.debug(f"Could not reconcile holding flag from live balance: {e}")
            return None
        # Empty != Zero (VIB-5155): a non-zero native balance whose USD
        # coerced to 0 means the price was UNMEASURED, not flat. Treating
        # that as 'not holding' would withhold the teardown risk-off swap
        # and strand the position. Native balance is truth; USD is only the
        # dust threshold. Mirrors snapshot.py _coerce_balance_result.
        if native > Decimal('0') and usd == Decimal('0'):
            # Funded but unpriceable: hold (cannot dust-floor without a price).
            live_holding = True
        else:
            live_holding = native > Decimal('0') and usd > self.holding_dust_usd
        if live_holding != self._holding_base:
            logger.warning(
                f"Reconciling _holding_base {self._holding_base} -> {live_holding} from live balance "
                f"({self.base_token} ${base_balance.balance_usd})"
            )
            self._holding_base = live_holding
            return True
        return False

    def reconcile_resumed_state(self, market):
        """Post-resume guardrail hook (VIB-5155 / ALM-2719).

        Called once by the runner after state is restored and before
        the first decide(). Re-derives `_holding_base` from live
        balance so a desynced restart cannot strand a position.
        """
        return self._reconcile_holding_base(market)

    def on_intent_executed(self, intent, success: bool, result):
        """Track swap executions for position tracking."""
        if not success:
            return
        intent_type = getattr(intent, "intent_type", None)
        if intent_type and intent_type.value == "SWAP":
            from_token = getattr(intent, 'from_token', None)
            to_token = getattr(intent, 'to_token', None)
            if to_token == self.base_token:
                self._holding_base = True
                self._last_signal = "buy"
                logger.info(f"Bought {self.base_token}")
            elif from_token == self.base_token:
                self._holding_base = False
                self._last_signal = "sell"
                logger.info(f"Sold {self.base_token}")

    def get_persistent_state(self):
        """Save position state for crash recovery."""
        return {"holding_base": self._holding_base, "last_signal": self._last_signal}

    def load_persistent_state(self, state):
        """Restore position state after restart.

        The restored `holding_base` value is only a HINT — it is
        reconciled against live on-chain balance before the first
        decision via reconcile_resumed_state() / _reconcile_holding_base()
        (VIB-5155 / ALM-2719). Never trust the cached flag alone.
        """
        if state:
            self._holding_base = state.get("holding_base", False)
            self._last_signal = state.get("last_signal", "neutral")

    # -------------------------------------------------------------------------
    # TEARDOWN (required) - implement so operators can safely close positions
    # Without these methods, operator close-requests are silently ignored.
    # Teardown-state posture (VIB-5464 / TD-06): whatever get_open_positions()
    # reads to know a position is open MUST survive a restart - persist it via
    # get_persistent_state()/load_persistent_state() (both sides), or re-derive
    # it purely from chain and set teardown_state_derived_from_chain = True.
    # See: docs/internal/blueprints/14-teardown-system.md
    # Exit assets: after positions close, the framework's consolidation phase
    # swaps recovered tokens to a target token by default. Declaring
    # get_teardown_profile() with preferred_asset_policy=TeardownAssetPolicy.KEEP_OUTPUTS
    # skips ONLY that consolidation swap — swap intents emitted by
    # generate_teardown_intents() itself are unaffected, so a no-swap mandate
    # also requires a swap-free unwind above.
    # -------------------------------------------------------------------------

    def get_open_positions(self):
        """Return all open positions for teardown preview.

        Reconciles the cached ``_holding_base`` flag from live balance first so
        a stale/false flag (e.g. after a desynced restart) cannot hide a base
        position the wallet actually holds (VIB-5155 / ALM-2719). Falls back to
        the cached hint only if a live snapshot is unavailable.
        """
        from datetime import UTC, datetime

        from almanak.framework.teardown import (
            PositionInfo,
            PositionType,
            TeardownPositionSummary,
        )

        snapshot = None
        try:
            snapshot = self.create_market_snapshot()
            self._reconcile_holding_base(snapshot)
        except Exception as e:
            logger.warning(
                f"get_open_positions: live-balance reconcile unavailable, "
                f"using cached holding flag: {e}"
            )

        positions = []

        if self._holding_base:
            # VALUE THE POSITION LIVE -- nothing in the framework back-fills
            # PositionInfo.value_usd. It is consumed verbatim: summed into the
            # teardown total and read by the max-acceptable-loss guard, where a
            # fabricated 0 silently buys the LOOSEST slippage tier at the exact
            # moment you are unwinding. Empty != Zero: when the read is
            # unavailable, emit 0 PAIRED WITH BOTH markers --
            # details["value_usd_unknown"] = True and
            # details["valuation_status"] = "no_path". Different consumers;
            # setting only one leaves the other treating this as a measured zero.
            #
            # BE PRECISE ABOUT WHAT THE MARKERS BUY YOU: they make the gap
            # VISIBLE, they do NOT restore the loss cap. "value_usd_unknown" is
            # read by the teardown CLI preview
            # (framework/cli/teardown_helpers.py), which prints "Value: unknown"
            # and drives the warning banner; "valuation_status" is read by the
            # portfolio valuer. The max-acceptable-loss guard itself
            # (``calculate_max_acceptable_loss``, framework/teardown/models.py)
            # still reads ONLY the summed numeric total and consults NEITHER
            # marker -- an unmeasured row therefore still contributes 0 and still
            # yields the most permissive tier. Closing that is VIB-5604. This is
            # exactly why valuing live above matters more than marking.
            #
            # DO NOT rely on the read RAISING. ``balance_usd()`` returns a plain
            # Decimal and does not raise for an unpriceable holding -- an illiquid
            # token or a degraded oracle yields a bare 0 while the balance is
            # non-zero, and a try/except alone would emit that as a MEASURED $0.
            # Inspect the pair semantically instead: a positive token balance
            # with a non-positive USD value is UNMEASURED. A genuinely zero
            # holding may stay a measured $0 -- that is a real answer.
            details = {"asset": self.base_token, "quote": self.quote_token}
            value_usd = Decimal("0")
            try:
                if snapshot is None:
                    raise RuntimeError("no market snapshot available")
                token_balance = snapshot.balance(self.base_token)
                value_usd = Decimal(str(token_balance.balance_usd))
                if Decimal(str(token_balance.balance)) > 0 and value_usd <= 0:
                    raise RuntimeError(
                        f"holding {token_balance.balance} {self.base_token} but USD "
                        f"value read back as {value_usd} -- unpriceable, not worthless"
                    )
            except Exception as e:
                logger.warning(
                    f"get_open_positions: {self.base_token} valuation unavailable: {e}"
                )
                value_usd = Decimal("0")
                details["valuation_status"] = "no_path"
                details["value_usd_unknown"] = True

            positions.append(
                PositionInfo(
                    position_type=PositionType.TOKEN,
                    position_id="keeperhub_swap_agent_base_token",
                    chain=self.chain,
                    protocol="uniswap_v3",
                    value_usd=value_usd,
                    details=details,
                )
            )

        return TeardownPositionSummary(
            deployment_id=getattr(self, "deployment_id", "keeperhub_swap_agent"),
            timestamp=datetime.now(UTC),  # reporting-only (decisions use market.timestamp)
            positions=positions,
        )

    def generate_teardown_intents(self, mode=None, market=None) -> list[AnyIntent]:
        """Generate intents to close all positions.

        Teardown goal: Swap all holdings back to quote token

        Live balance is truth: reconcile the cached ``_holding_base`` flag from
        the provided ``market`` (or a freshly-built snapshot) BEFORE deciding
        whether to emit the risk-off swap. A stale/false flag must never block
        a valid exit (VIB-5155 / ALM-2719).
        """
        from almanak.framework.teardown import TeardownMode

        try:
            self._reconcile_holding_base(market or self.create_market_snapshot())
        except Exception as e:
            logger.warning(
                f"generate_teardown_intents: live-balance reconcile unavailable, "
                f"using cached holding flag: {e}"
            )

        intents: list[AnyIntent] = []

        if self._holding_base:
            max_slippage = Decimal("0.03") if mode == TeardownMode.HARD else Decimal("0.005")
            intents.append(
                Intent.swap(
                    from_token=self.base_token,
                    to_token=self.quote_token,
                    amount="all",
                    max_slippage=max_slippage,
                )
            )

        return intents


if __name__ == "__main__":
    print("=" * 60)
    print("KeeperhubSwapAgentStrategy")
    print("=" * 60)
    print(f"Strategy Name: {KeeperhubSwapAgentStrategy.STRATEGY_NAME}")
    print(f"Supported Chains: {KeeperhubSwapAgentStrategy.SUPPORTED_CHAINS}")
    print(f"Supported Protocols: {KeeperhubSwapAgentStrategy.SUPPORTED_PROTOCOLS}")
    print(f"Intent Types: {KeeperhubSwapAgentStrategy.INTENT_TYPES}")
    print("\nTo run this strategy:")
    print("  uv run almanak strat run --once")
