"""
Tests for keeperhub_swap_agent strategy.

Generated by: almanak strat new
Template: ta_swap

These tests are a starting point -- extend them as your strategy evolves.
They cover: init, decide(), error handling, state transitions, persistence
round-trip, teardown intents, and common edge cases (zero balance, zero price).
"""

import hashlib
import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from almanak.framework.market.models import RSIData, TokenBalance
from almanak.framework.market.testing import seeded
from strategy import KeeperhubSwapAgentStrategy

# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def config() -> dict:
    """Load test configuration from config.json, falling back to a minimal stub."""
    config_path = Path(__file__).parent.parent / "config.json"
    if config_path.exists():
        with open(config_path) as f:
            return json.load(f)
    return {
        "deployment_id": "test-strategy-001",
        "chain": "arbitrum",
    }


@pytest.fixture
def strategy(config: dict) -> KeeperhubSwapAgentStrategy:
    """Fresh strategy instance for each test (no shared mutable state)."""
    return KeeperhubSwapAgentStrategy(
        config=config,
        chain=config.get("chain", "arbitrum"),
        wallet_address="0x" + "1" * 40,
    )


def _load_test_config() -> dict:
    """config.json drives the seeded market (module-level so helpers can use it)."""
    config_path = Path(__file__).parent.parent / "config.json"
    if config_path.exists():
        with open(config_path) as f:
            return json.load(f)
    return {"deployment_id": "test-strategy-001", "chain": "arbitrum"}


_TEST_CONFIG = _load_test_config()

# Config keys that name tokens the strategy may query. Symbols found here get
# seeded prices/balances so decide() sees a funded, priced market.
_TOKEN_CONFIG_KEYS = (
    "base_token", "quote_token", "target_token", "stable_token",
    "collateral_token", "borrow_token", "supply_token", "deposit_token",
    "stake_token",
    "token_x", "token_y", "token0", "token1",
)

T0 = datetime(2026, 1, 1, 12, 0, tzinfo=UTC)


def _config_tokens() -> list[str]:
    tokens: list[str] = []
    for key in _TOKEN_CONFIG_KEYS:
        value = _TEST_CONFIG.get(key)
        if isinstance(value, str) and value:
            tokens.append(value)
    for entry in _TEST_CONFIG.get("token_funding", []) or []:
        symbol = entry.get("symbol") if isinstance(entry, dict) else None
        if isinstance(symbol, str) and symbol:
            tokens.append(symbol)
    for pool_key in ("pool", "lp_pool"):
        pool = _TEST_CONFIG.get(pool_key)
        if isinstance(pool, str) and "/" in pool:
            tokens.extend(part for part in pool.split("/")[:2] if part)
    # Snapshot lookups are case-insensitive, so seed each symbol exactly as
    # config.json spells it and dedupe case-insensitively (first spelling
    # wins). Fall back to common majors so the harness still seeds something
    # before config.json is filled in.
    seen: dict[str, str] = {}
    for t in tokens:
        seen.setdefault(t.upper(), t)
    return list(seen.values()) or ["WETH", "USDC"]


# Per-token test prices. A SINGLE scalar for every symbol makes an inverted
# price basis -- using the quote token's price where the base token's belongs --
# arithmetically invisible: if USDC and WETH both read $2000 then base/quote and
# quote/base produce the same number and every assertion still passes. That
# inversion is the single most damaging unit bug in strategy code, so the harness
# must be able to see it. Keep these values DISTINCT and non-round.
_TEST_PRICES: dict[str, Decimal] = {
    "USDC": Decimal("1"),
    "USDT": Decimal("1"),
    "DAI": Decimal("1"),
    "USDC.E": Decimal("1"),
    "USDS": Decimal("1"),
    "SUSDS": Decimal("1"),
    "WETH": Decimal("2000"),
    "ETH": Decimal("2000"),
    "STETH": Decimal("2000"),
    "WSTETH": Decimal("2360"),
    "WBTC": Decimal("60000"),
    "CBBTC": Decimal("60000"),
    "AVAX": Decimal("40"),
    "WAVAX": Decimal("40"),
    "ARB": Decimal("0.85"),
    "OP": Decimal("1.70"),
    "LINK": Decimal("15"),
}
def _test_price_for(token: str) -> Decimal:
    """Distinct, stable per-token price so unit/basis errors surface in assertions.

    An unknown symbol gets a price DERIVED FROM THE SYMBOL rather than one shared
    constant. A single fallback would reproduce the bug this fixture exists to
    expose, one level down: two custom tokens both priced at the same number make
    a base/quote inversion between THEM invisible again, exactly as USDC and WETH
    both reading $2000 did. The derivation is a stable hash of the symbol, so it
    is deterministic across runs (no ordering or seed dependence) while still
    separating any two distinct symbols.

    The band is 3-953, deliberately overlapping neither the stablecoin 1 nor
    WETH's 2000, and never zero — a zero here would silently exercise the
    unpriced-market path in tests that meant to use a healthy market.
    """
    upper = token.upper()
    known = _TEST_PRICES.get(upper)
    if known is not None:
        return known
    # Stable across processes: hashlib, not builtin hash() (which is salted).
    digest = hashlib.sha256(upper.encode()).hexdigest()
    return Decimal(3 + int(digest[:8], 16) % 950) + (Decimal(int(digest[8:10], 16) % 100) / Decimal(100))


def _make_market(
    *,
    price: Decimal | None = None,
    balance: Decimal = Decimal("100"),
    balance_usd: Decimal | None = None,
    rsi: Decimal = Decimal("50"),
    timestamp: datetime = T0,
):
    """Build a seeded MarketSnapshot for the tokens config.json names.

    Unseeded data (funding rates, position health, ...) raises the SDK's
    data-unavailable errors. Drive time-based tests by passing different
    ``timestamp`` values to successive decide() calls.

    ``price`` defaults to None, which seeds each token with its own realistic
    price from ``_TEST_PRICES`` (see the note there -- a uniform price hides
    inverted-basis bugs). Pass an explicit ``price`` to force ONE value across
    every token, which is what the zero-price/degraded-oracle tests want.

    ``balance_usd`` resolution, in order:
      1. explicit value  -> used verbatim for every token
      2. explicit price  -> derived as ``balance * price``
      3. neither         -> a healthy flat default

    Rule 2 matters: forcing ``price=0`` must NOT leave the wallet claiming a
    six-figure USD balance. A market that cannot price an asset does not know
    what the holding is worth, and a fixture that asserts otherwise lets a
    strategy walk straight past its own USD-denominated guards -- the harness
    would then be certifying behaviour that cannot happen in production.
    """
    period = int(_TEST_CONFIG.get("rsi_period", 14) or 14)
    tokens = _config_tokens()

    def _usd_for(token: str) -> Decimal:
        if balance_usd is not None:
            return balance_usd
        if price is not None:
            return balance * price
        return Decimal("100000")

    return seeded(
        chain="arbitrum",
        wallet_address="0x" + "1" * 40,
        prices={
            token: (price if price is not None else _test_price_for(token)) for token in tokens
        },
        balances={
            token: TokenBalance(symbol=token, balance=balance, balance_usd=_usd_for(token))
            for token in tokens
        },
        indicators={f"{token}:rsi:{period}": RSIData(value=rsi, period=period) for token in tokens},
        timestamp=timestamp,
    )


@pytest.fixture
def market():
    """Seeded MarketSnapshot with healthy defaults (all config tokens funded)."""
    return _make_market()


def _make_mock_intent(intent_type_value: str, **attrs: object) -> MagicMock:
    """Build a minimal intent mock with intent_type.value == intent_type_value.

    Extra kwargs become attributes on the returned mock (e.g. from_token).
    """
    intent = MagicMock()
    intent.intent_type.value = intent_type_value
    for key, value in attrs.items():
        setattr(intent, key, value)
    return intent


def _make_mock_result(**attrs: object) -> MagicMock:
    """Build a minimal execution-result mock (used by on_intent_executed tests)."""
    result = MagicMock()
    result.extracted_data = attrs.pop("extracted_data", {})
    for key, value in attrs.items():
        setattr(result, key, value)
    return result


# ---------------------------------------------------------------------------
# Base tests: init, decide(), error handling, get_status
# ---------------------------------------------------------------------------


class TestKeeperhubSwapAgentStrategyBasics:
    """Core contract: strategy constructs, decides, and reports status cleanly."""

    def test_initialization(self, strategy: KeeperhubSwapAgentStrategy) -> None:
        """Strategy reports the chain and wallet it was constructed with."""
        assert strategy.chain == "arbitrum"
        assert strategy.wallet_address == "0x" + "1" * 40

    def test_decide_returns_intent_or_none(
        self, strategy: KeeperhubSwapAgentStrategy, market
    ) -> None:
        """decide() must return None, an Intent (with intent_type), or an IntentSequence.

        Any other return type breaks the framework's intent compiler.
        """
        result = strategy.decide(market)
        # Accept three valid return types: None, Intent (has .intent_type),
        # or IntentSequence (has .intents).
        assert (
            result is None
            or hasattr(result, "intent_type")
            or hasattr(result, "intents")
        ), (
            f"decide() returned {type(result).__name__} which is not a "
            "valid Intent / IntentSequence / None"
        )

    def test_decide_handles_market_errors_gracefully(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """When market data is unavailable (bare snapshot), decide() must return hold/None, not raise."""
        market = seeded(chain="arbitrum", timestamp=T0)

        result = strategy.decide(market)

        # Must not raise. Must return a hold intent or None.
        assert (
            result is None
            or hasattr(result, "intent_type")
            or hasattr(result, "intents")
        ), "decide() returned non-Intent on error"
        if result is not None and hasattr(result, "intent_type"):
            intent_type = getattr(result.intent_type, "value", str(result.intent_type))
            assert intent_type == "HOLD", (
                f"Expected HOLD on error, got {intent_type}. "
                f"Reason: {getattr(result, 'reason', '<no reason>')}"
            )

    def test_get_status_contract(self, strategy: KeeperhubSwapAgentStrategy) -> None:
        """get_status() returns a dict with at minimum 'strategy' and 'chain'."""
        status = strategy.get_status()

        assert isinstance(status, dict), "get_status() must return a dict"
        assert "strategy" in status, "status must include 'strategy' key"
        assert "chain" in status, "status must include 'chain' key"
        assert status["chain"] == "arbitrum"


# ---------------------------------------------------------------------------
# Edge cases: degenerate market inputs
# ---------------------------------------------------------------------------

# Intent types this template may still emit when the oracle price is 0.
# HOLD is always allowed. Anything else listed here is sized in TOKEN UNITS,
# never in USD, so a dead oracle does not make its size meaningless -- keep
# this set minimal, since every extra entry is a hole in the assertion below.
_ZERO_PRICE_ALLOWED_INTENTS = {"HOLD"}


class TestKeeperhubSwapAgentStrategyEdgeCases:
    """Degenerate market inputs must not crash the strategy."""

    def test_decide_with_zero_balance_does_not_raise(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """With zero balance, decide() should return cleanly (typically a hold)."""
        market = _make_market(balance=Decimal("0"), balance_usd=Decimal("0"))
        result = strategy.decide(market)
        assert (
            result is None
            or hasattr(result, "intent_type")
            or hasattr(result, "intents")
        )

    def test_decide_with_zero_price_does_not_raise(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """A price=0 (bad oracle) must not raise AND must not trade.

        Strategies that size by ``amount_usd / price`` are especially vulnerable.
        Not raising is only half the contract: a zero oracle price means the
        market is UNPRICED, and sizing a live trade off an unpriced market is
        the failure this test exists to catch. Asserting only that the return
        value is Intent-shaped would pass a strategy that happily submits a SWAP
        sized off a $0 price -- so the intent type is asserted too, matching
        ``test_decide_handles_market_errors_gracefully``.
        """
        # Sweep the signal axis, not just the default neutral one. With the
        # default rsi=50 an indicator-driven template returns "no signal" and
        # never REACHES its buy/sell sizing at all -- so the assertion below
        # would pass while an unguarded ``trade_size_usd / price`` sat one
        # signal away. 20/80 straddle the conventional oversold/overbought
        # thresholds; templates that ignore RSI are unaffected.
        for _rsi in (Decimal("50"), Decimal("20"), Decimal("80")):
            self._assert_zero_price_holds(strategy, _rsi)

    @staticmethod
    def _assert_zero_price_holds(strategy, rsi_value: Decimal) -> None:
        market = _make_market(price=Decimal("0"), rsi=rsi_value)
        try:
            result = strategy.decide(market)
        except ZeroDivisionError as exc:
            pytest.fail(
                "decide() raised ZeroDivisionError on zero price; "
                "guard with ``if price > 0`` before sizing trades: "
                f"{exc}"
            )
        assert (
            result is None
            or hasattr(result, "intent_type")
            or hasattr(result, "intents")
        )

        # An unpriced market must not produce a live trade.
        emitted = []
        if result is not None:
            emitted = list(getattr(result, "intents", None) or [result])
        for item in emitted:
            if not hasattr(item, "intent_type"):
                continue
            intent_type = getattr(item.intent_type, "value", str(item.intent_type))
            assert intent_type in _ZERO_PRICE_ALLOWED_INTENTS, (
                f"decide() emitted {intent_type} on a ZERO price. An unpriced "
                f"market must produce HOLD -- sizing a trade off a $0 oracle "
                f"reads as free size. Guard with ``if price > 0``. "
                f"Reason: {getattr(item, 'reason', '<no reason>')}"
            )


# ---------------------------------------------------------------------------
# Teardown: close-position safety (operators rely on this)
# ---------------------------------------------------------------------------


class TestKeeperhubSwapAgentStrategyTeardown:
    """Teardown methods must honour the operator safety contract.

    See: docs/internal/blueprints/14-teardown-system.md
    """

    def test_teardown_methods_exist(self, strategy: KeeperhubSwapAgentStrategy) -> None:
        """Both teardown methods are implemented (not inherited as no-ops)."""
        assert hasattr(strategy, "get_open_positions")
        assert hasattr(strategy, "generate_teardown_intents")
        assert callable(strategy.get_open_positions)
        assert callable(strategy.generate_teardown_intents)

    def test_get_open_positions_returns_summary(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """get_open_positions() returns a TeardownPositionSummary (or None)."""
        summary = strategy.get_open_positions()
        if summary is not None:
            assert hasattr(summary, "positions"), (
                "summary must be a TeardownPositionSummary with .positions"
            )
            assert isinstance(summary.positions, list)

    def test_generate_teardown_intents_soft_returns_list(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """Must return a list (possibly empty) of Intent-like objects."""
        from almanak.framework.teardown import TeardownMode

        strategy._holding_base = True
        intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT)
        assert isinstance(intents, list), (
            f"Must return a list, got {type(intents).__name__}"
        )

    def test_generate_teardown_intents_hard_returns_list(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """HARD mode must also return a list (possibly empty)."""
        from almanak.framework.teardown import TeardownMode

        strategy._holding_base = True
        intents = strategy.generate_teardown_intents(mode=TeardownMode.HARD)
        assert isinstance(intents, list)

    def test_generate_teardown_intents_soft_mode_with_position(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """With a position held, SOFT teardown generates at least one intent."""
        from almanak.framework.teardown import TeardownMode

        # Simulate a held position
        strategy._holding_base = True

        intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT)
        assert isinstance(intents, list), "generate_teardown_intents() must return a list"
        assert len(intents) > 0, "Expected non-empty teardown intents when position is held"
        for intent in intents:
            assert hasattr(intent, "intent_type"), (
                f"Teardown returned non-Intent: {type(intent).__name__}"
            )

    def test_generate_teardown_intents_hard_mode_with_position(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """With a position held, HARD teardown also generates intents."""
        from almanak.framework.teardown import TeardownMode

        strategy._holding_base = True

        intents = strategy.generate_teardown_intents(mode=TeardownMode.HARD)
        assert isinstance(intents, list)
        assert len(intents) > 0, "Expected non-empty teardown intents in HARD mode"

    def test_generate_teardown_intents_hard_mode_higher_slippage(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """HARD mode should tolerate at least as much slippage as SOFT.

        Teardown goal in HARD mode is speed over cost; slippage must not
        be tighter than SOFT.
        """
        from almanak.framework.teardown import TeardownMode

        strategy._holding_base = True
        soft_intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT)
        # Reset state for a fresh HARD run (position_setup applied twice)
        strategy._holding_base = True
        hard_intents = strategy.generate_teardown_intents(mode=TeardownMode.HARD)

        def _swap_slippages(intents):
            return [
                getattr(i, "max_slippage", None)
                for i in intents
                if getattr(i.intent_type, "value", str(i.intent_type)) == "SWAP"
                and getattr(i, "max_slippage", None) is not None
            ]

        soft_slippages = _swap_slippages(soft_intents)
        hard_slippages = _swap_slippages(hard_intents)
        if soft_slippages and hard_slippages:
            assert max(hard_slippages) >= max(soft_slippages), (
                f"HARD slippage {max(hard_slippages)} must be >= "
                f"SOFT slippage {max(soft_slippages)}"
            )

    def test_get_open_positions_reports_held_position(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """After faking a position, get_open_positions() should list it."""
        strategy._holding_base = True

        summary = strategy.get_open_positions()
        assert summary is not None, "get_open_positions() must not return None"
        positions = getattr(summary, "positions", None)
        assert positions is not None, "summary must have a .positions attribute"
        assert len(positions) >= 1, "Expected at least one position to be reported"

    def test_generate_teardown_intents_no_position_returns_empty_list(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """A fresh strategy with no open position returns an empty list (no raise).

        The held-position path is covered above; this pins the []/no-raise
        contract on a FRESH strategy. ``create_market_snapshot`` is stubbed to a
        no-position snapshot so the no-``market``-arg fallback stays network-free
        (the teardown helper reads price/balance/position_health off it).
        """
        from almanak.framework.teardown import TeardownMode

        _empty = MagicMock()
        _empty.price.return_value = Decimal("1")
        _empty_bal = MagicMock()
        _empty_bal.balance = Decimal("0")
        _empty.balance.return_value = _empty_bal
        _empty_health = MagicMock()
        _empty_health.collateral_value_usd = Decimal("0")
        _empty_health.debt_value_usd = Decimal("0")
        _empty_health.lltv = Decimal("0.83")
        _empty_health.health_factor = Decimal("0")
        _empty.position_health.return_value = _empty_health
        strategy.create_market_snapshot = lambda: _empty

        intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT)
        assert isinstance(intents, list), (
            f"Must return a list, got {type(intents).__name__}"
        )
        assert intents == [], "fresh strategy (no position) must yield no teardown intents"



# ---------------------------------------------------------------------------
# State machine: on_intent_executed transitions
# ---------------------------------------------------------------------------

import copy  # noqa: E402 -- used by failure-path deepcopy assertions below


class TestKeeperhubSwapAgentStrategyStateMachine:
    """on_intent_executed() must advance / clear state correctly."""

    @pytest.mark.parametrize(
        "intent_type_value,intent_attrs,result_attrs,pre_state,expected",
        [
        pytest.param(
            'SWAP',
            {'from_token': 'USDC', 'to_token': 'WETH'},
            {},
            {'_holding_base': False, '_last_signal': 'neutral'},
            {'_holding_base': True, '_last_signal': 'buy'},
            id='swap_to_base_sets_holding_and_buy_latch',
        ),
        pytest.param(
            'SWAP',
            {'from_token': 'WETH', 'to_token': 'USDC'},
            {},
            {'_holding_base': True, '_last_signal': 'buy'},
            {'_holding_base': False, '_last_signal': 'sell'},
            id='swap_from_base_clears_holding_and_sell_latch',
        ),
        ],
    )
    def test_on_intent_executed_advances_state(
        self,
        strategy: KeeperhubSwapAgentStrategy,
        intent_type_value: str,
        intent_attrs: dict,
        result_attrs: dict,
        pre_state: dict,
        expected: dict,
    ) -> None:
        """Each template-specific transition should update the right state field."""
        # Seed the pre-state onto the strategy instance.
        for field, value in pre_state.items():
            setattr(strategy, field, value)

        intent = _make_mock_intent(intent_type_value, **intent_attrs)
        result = _make_mock_result(**result_attrs)

        strategy.on_intent_executed(intent, success=True, result=result)

        # Special-case: "<field>_len" asserts against len(strategy.<field>)
        for field, expected_value in expected.items():
            if field.endswith("_len"):
                real_field = field[: -len("_len")]
                actual_len = len(getattr(strategy, real_field))
                assert actual_len == expected_value, (
                    f"Expected len({real_field}) == {expected_value}, got {actual_len}"
                )
            else:
                actual = getattr(strategy, field)
                assert actual == expected_value, (
                    f"Expected {field} == {expected_value!r}, got {actual!r}"
                )

    def test_on_intent_executed_failure_does_not_credit_state(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """A FAILED intent must never ADVANCE or CREDIT position state.

        TWO PHASES, because either alone has a blind spot:

        * **Phase A, from the FRESH state: nothing may change at all.** This is
          full-state equality, and it is what catches a handler ADVANCING a
          state machine on failure -- e.g. a failed PERP_OPEN that still sets
          ``_trade_state = HEDGED``, leaving the strategy believing it is hedged
          with no hedge on-chain. Most templates hold their primary state in a
          ``StrEnum``, and a ``StrEnum`` IS a ``str``: it is neither numeric nor
          a collection, so the Phase-B contract below cannot see it move. Phase A
          is safe from the fresh state precisely because a correct handler has
          nothing to revert there -- any diff is the handler inventing state.

        * **Phase B, from a SEEDED mid-flight state: no credit.** Phase A alone
          is vacuous for quantities: a fresh strategy is already zeroed, so a
          handler that zeroes on failure produces no diff and the assertion
          passes no matter what it does. Seeding first makes a wrong mutation
          observable. The contract here is deliberately narrow so it does not
          punish correct code:

            - numeric fields must NOT increase -- growth on a failed intent is
              phantom credit, booking size that never executed on-chain
            - collections must NOT grow -- same failure, for trade/position lists

          Reverting a transitional state to a stable one, or ZEROING a quantity,
          is legitimate failure handling and stays allowed in Phase B.

        Do not collapse these into one phase. Phase B alone was a REGRESSION
        against full-state equality: it silently dropped enum coverage, and a
        mutation that credited state on failure passed it while the older broad
        assertion caught it.

        What this still canNOT check is whether your handler reverts to the
        RIGHT state -- that is strategy-specific. Add an explicit assertion for
        your own transition below.
        """
        tracked_fields = [
            f for f in ('_holding_base', '_last_signal') if hasattr(strategy, f)
        ]

        def _snapshot() -> dict:
            return {f: copy.deepcopy(getattr(strategy, f)) for f in tracked_fields}

        def _restore(state: dict) -> None:
            for f, value in state.items():
                setattr(strategy, f, copy.deepcopy(value))

        # Captured BEFORE any seeding. Phase B deliberately mutates the strategy,
        # and that mutation must not leak into the NEXT intent type's Phase A --
        # otherwise "from the fresh state" is a lie from the second iteration on,
        # and a handler doing exactly what Phase B declares legitimate (reverting
        # a transitional state, zeroing a quantity) would trip Phase A's
        # full-state equality and fail correct code.
        initial_state = _snapshot()

        # Fire EVERY intent type this template branches on, not just one. The
        # callback dispatches on intent_type, so a single hardcoded type would
        # leave the other failure branches unexercised -- a broken LP_OPEN or
        # PERP_OPEN failure path could credit state while this test stayed green.
        for intent_type_value in ('SWAP',):
            # ---- Phase A: from the fresh state, NOTHING may change. ----
            _restore(initial_state)
            fresh_before = _snapshot()
            strategy.on_intent_executed(
                _make_mock_intent(intent_type_value), success=False, result=_make_mock_result()
            )
            fresh_after = _snapshot()
            assert fresh_before == fresh_after, (
                f"A failed {intent_type_value} intent MUTATED state from the "
                f"initial state. Nothing was executed on-chain, so there is "
                f"nothing to record and nothing to revert. Diff: "
                f"{[(f, fresh_before[f], fresh_after[f]) for f in tracked_fields if fresh_before[f] != fresh_after[f]]}"
            )

            # ---- Phase B: from a seeded mid-flight state, no CREDIT. ----
            for f in tracked_fields:
                current = getattr(strategy, f)
                if isinstance(current, bool):
                    setattr(strategy, f, True)
                elif isinstance(current, Decimal):
                    setattr(strategy, f, Decimal("3"))
                elif isinstance(current, int):
                    setattr(strategy, f, 3)
                elif isinstance(current, list):
                    setattr(strategy, f, [{"seeded": True}])
                elif current is None:
                    setattr(strategy, f, Decimal("3"))

            before = _snapshot()

            intent = _make_mock_intent(intent_type_value)
            result = _make_mock_result()
            strategy.on_intent_executed(intent, success=False, result=result)

            for f in tracked_fields:
                old = before[f]
                new = getattr(strategy, f)
                numeric = (int, float, Decimal)
                if (
                    isinstance(old, numeric)
                    and isinstance(new, numeric)
                    and not isinstance(old, bool)
                    and not isinstance(new, bool)
                ):
                    assert Decimal(str(new)) <= Decimal(str(old)), (
                        f"{f} INCREASED on a failed {intent_type_value} intent "
                        f"({old} -> {new}). A failed intent must never credit "
                        f"state -- that books size which never executed on-chain."
                    )
                elif isinstance(old, list | dict | set) and isinstance(new, list | dict | set):
                    assert len(new) <= len(old), (
                        f"{f} GREW on a failed {intent_type_value} intent "
                        f"(len {len(old)} -> {len(new)}). A failed intent must "
                        f"never append a position or trade record."
                    )


# ---------------------------------------------------------------------------
# Persistence: get_persistent_state / load_persistent_state round-trip
# ---------------------------------------------------------------------------


class TestKeeperhubSwapAgentStrategyPersistence:
    """State must survive a save / load cycle so restarts don't lose context."""

    def test_get_persistent_state_returns_dict(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """get_persistent_state() returns a JSON-serializable dict."""
        state = strategy.get_persistent_state()
        assert isinstance(state, dict), "persistent state must be a dict"
        try:
            json.dumps(state, default=str)
        except (TypeError, ValueError) as exc:
            pytest.fail(f"persistent state is not JSON-serializable: {exc}")

    def test_load_persistent_state_round_trip(
        self, strategy: KeeperhubSwapAgentStrategy, config: dict
    ) -> None:
        """Save state -> fresh instance -> load -> state preserved.

        This is the lifecycle the runner performs on restart. A break here
        means the strategy will 'forget' open positions after a crash.
        """
        sample = {'holding_base': True, 'last_signal': 'buy'}
        # Seed the current instance with the sample state
        strategy.load_persistent_state(sample)

        saved = strategy.get_persistent_state()
        assert isinstance(saved, dict)

        # Load into a brand-new instance
        fresh = KeeperhubSwapAgentStrategy(
            config=config,
            chain=config.get("chain", "arbitrum"),
            wallet_address="0x" + "1" * 40,
        )
        fresh.load_persistent_state(saved)

        # Both instances should now agree on every field they persist.
        fresh_saved = fresh.get_persistent_state()
        for key in saved:
            assert fresh_saved.get(key) == saved.get(key), (
                f"Round-trip lost key={key}: {saved.get(key)!r} -> {fresh_saved.get(key)!r}"
            )

    def test_load_persistent_state_with_empty_dict_does_not_raise(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """Empty / missing state on first run must be handled (no crash)."""
        strategy.load_persistent_state({})
        assert isinstance(strategy.get_persistent_state(), dict)


# ---------------------------------------------------------------------------
# Resume-state reconciliation (VIB-5155 / ALM-2719)
#
# A stale/false cached side-state flag must never HOLD-lock a valid exit:
# live wallet balance is truth, the persisted flag is only a hint.
# ---------------------------------------------------------------------------


class TestKeeperhubSwapAgentStrategyResumeReconcile:
    """Cached side-state flag is reconciled from live balance, not trusted blindly."""

    def test_reconcile_resumed_state_flips_stale_false_flag(
        self, strategy: KeeperhubSwapAgentStrategy, market
    ) -> None:
        """Resume hook flips a stale FALSE flag to True when the wallet holds base.

        Simulates a desynced restart: persisted state said 'not holding base'
        but the wallet actually holds base. The post-resume guardrail must
        correct the flag from live balance and report the correction.
        """
        # Persisted (desynced) state: flag false despite holding base on-chain.
        strategy.load_persistent_state({"holding_base": False, "last_signal": "buy"})
        assert strategy._holding_base is False

        corrected = strategy.reconcile_resumed_state(market)

        assert corrected is True, "desync should be detected and corrected"
        assert strategy._holding_base is True, "flag must follow live balance (truth)"

    def test_reconcile_resumed_state_noop_when_already_agrees(
        self, strategy: KeeperhubSwapAgentStrategy, market
    ) -> None:
        """No desync -> hook returns False and leaves the flag unchanged."""
        strategy.load_persistent_state({"holding_base": True, "last_signal": "buy"})
        corrected = strategy.reconcile_resumed_state(market)
        assert corrected is False
        assert strategy._holding_base is True

    def test_teardown_exits_despite_stale_false_flag(
        self, strategy: KeeperhubSwapAgentStrategy, market
    ) -> None:
        """THE FUND-SAFETY CASE: balance-true-but-flag-false must still exit.

        Wallet holds base, but the resumed flag is False. A teardown request
        (operator risk-off) must still generate the exit swap by reconciling
        from live balance -- the cached flag must not block the exit.
        """
        from almanak.framework.teardown import TeardownMode

        # Desynced resume: flag false, but the wallet holds base (market
        # reports a funded base balance).
        strategy.load_persistent_state({"holding_base": False, "last_signal": "buy"})
        assert strategy._holding_base is False

        intents = strategy.generate_teardown_intents(
            mode=TeardownMode.SOFT, market=market
        )

        assert len(intents) > 0, (
            "teardown must reconcile from live balance and exit even when the "
            "cached holding flag is stale/false (VIB-5155)"
        )
        swap = intents[0]
        assert getattr(swap, "from_token", None) == strategy.base_token
        assert getattr(swap, "to_token", None) == strategy.quote_token

    def test_teardown_no_exit_when_truly_flat(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """Symmetric guard: flag true but wallet flat -> no phantom exit swap.

        Live balance is truth in BOTH directions. A stale TRUE flag on an empty
        wallet must not generate a swap of funds the wallet does not hold.
        """
        from almanak.framework.teardown import TeardownMode

        flat = _make_market(balance=Decimal("0"), balance_usd=Decimal("0"))
        strategy.load_persistent_state({"holding_base": True, "last_signal": "buy"})

        intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT, market=flat)

        assert intents == [], "no exit swap when the wallet is genuinely flat"
        assert strategy._holding_base is False, "stale TRUE flag corrected to flat"

    def test_teardown_exits_when_base_held_but_unpriceable(
        self, strategy: KeeperhubSwapAgentStrategy
    ) -> None:
        """Empty != Zero: a funded base token whose USD is UNMEASURED still exits.

        When the price oracle cannot price the base token, MarketSnapshot
        coerces ``balance_usd`` to ``Decimal('0')`` while the native balance
        stays non-zero (VIB-4843 sentinel). Reconciling on USD alone would read
        that as 'flat', clear the holding flag, and emit no teardown swap --
        stranding a real position. Native balance is truth: the exit must still
        fire (VIB-5155 / ALM-2719).
        """
        from almanak.framework.teardown import TeardownMode

        # Funded but unpriceable: non-zero native balance, USD coerced to 0.
        unpriceable = _make_market(balance=Decimal("5"), balance_usd=Decimal("0"))
        strategy.load_persistent_state({"holding_base": True, "last_signal": "buy"})

        intents = strategy.generate_teardown_intents(mode=TeardownMode.SOFT, market=unpriceable)

        assert len(intents) > 0, (
            "teardown must exit on native balance even when USD price is "
            "unmeasured -- a couldn't-price $0 must not strand a held position"
        )
        assert strategy._holding_base is True, "non-zero native holding stays 'holding'"

